"""add facility.phone

Revision ID: 5e076ce95011
Revises: cc7536518227
Create Date: 2025-10-05 16:01:23.189270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e076ce95011'
down_revision: Union[str, Sequence[str], None] = 'cc7536518227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilities', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facilities', 'phone')
    # ### end Alembic commands ###
