"""initial schema

Revision ID: 86904ad00376
Revises: 9f2deb4aa65d
Create Date: 2025-10-09 17:33:03.514529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86904ad00376'
down_revision: Union[str, None] = '9f2deb4aa65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credential_types'))
    )
    op.create_index(op.f('ix_credential_types_code'), 'credential_types', ['code'], unique=True)
    op.create_table('facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.Enum('HOSPITAL', 'HOME_HEALTH', 'SENIOR_CARE', 'REHAB_CENTER', 'OTHER', name='industry'), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=512), nullable=True),
    sa.Column('phone_e164', sa.String(length=32), nullable=True),
    sa.Column('company_size_min', sa.Integer(), nullable=True),
    sa.Column('company_size_max', sa.Integer(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('hq_address_line1', sa.String(length=255), nullable=True),
    sa.Column('hq_address_line2', sa.String(length=255), nullable=True),
    sa.Column('hq_city', sa.String(length=120), nullable=True),
    sa.Column('hq_state_province', sa.String(length=120), nullable=True),
    sa.Column('hq_postal_code', sa.String(length=20), nullable=True),
    sa.Column('hq_country', sa.String(length=120), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(company_size_min IS NULL OR company_size_max IS NULL) OR (company_size_min <= company_size_max)', name=op.f('ck_facilities_ck_facility_size_min_le_max')),
    sa.CheckConstraint('(founded_year IS NULL) OR (founded_year BETWEEN 1800 AND 2100)', name=op.f('ck_facilities_ck_facility_founded_year_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilities'))
    )
    op.create_index(op.f('ix_facilities_hq_city'), 'facilities', ['hq_city'], unique=False)
    op.create_index(op.f('ix_facilities_hq_country'), 'facilities', ['hq_country'], unique=False)
    op.create_index(op.f('ix_facilities_hq_postal_code'), 'facilities', ['hq_postal_code'], unique=False)
    op.create_index(op.f('ix_facilities_hq_state_province'), 'facilities', ['hq_state_province'], unique=False)
    op.create_index(op.f('ix_facilities_industry'), 'facilities', ['industry'], unique=False)
    op.create_index('ix_facilities_industry_city', 'facilities', ['industry', 'hq_city'], unique=False)
    op.create_index('ix_facilities_industry_state', 'facilities', ['industry', 'hq_state_province'], unique=False)
    op.create_index(op.f('ix_facilities_legal_name'), 'facilities', ['legal_name'], unique=True)
    op.create_index(op.f('ix_facilities_phone_e164'), 'facilities', ['phone_e164'], unique=False)
    op.create_table('specialty_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialty_types'))
    )
    op.create_index(op.f('ix_specialty_types_code'), 'specialty_types', ['code'], unique=True)
    op.create_table('workers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('title', sa.Enum('RN', 'LPN', 'CNA', 'CAREGIVER', 'SUPPORT', name='workertitle'), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=512), nullable=True),
    sa.Column('resume_url', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state_province', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('education_level', sa.Enum('HIGHSCHOOL', 'COLLEGE', name='educationlevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workers'))
    )
    op.create_index(op.f('ix_workers_city'), 'workers', ['city'], unique=False)
    op.create_index(op.f('ix_workers_full_name'), 'workers', ['full_name'], unique=False)
    op.create_index(op.f('ix_workers_postal_code'), 'workers', ['postal_code'], unique=False)
    op.create_index(op.f('ix_workers_state_province'), 'workers', ['state_province'], unique=False)
    op.create_index(op.f('ix_workers_title'), 'workers', ['title'], unique=False)
    op.create_index('ix_workers_title_city', 'workers', ['title', 'city'], unique=False)
    op.create_index('ix_workers_title_state', 'workers', ['title', 'state_province'], unique=False)
    op.create_table('endorsements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('has_badge', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_endorsements_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_endorsements_worker_id_workers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_endorsements')),
    sa.UniqueConstraint('worker_id', 'facility_id', name='uq_endorsement_once_per_facility')
    )
    op.create_index(op.f('ix_endorsements_facility_id'), 'endorsements', ['facility_id'], unique=False)
    op.create_index(op.f('ix_endorsements_worker_id'), 'endorsements', ['worker_id'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('position_title', sa.String(length=160), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_experiences_worker_id_workers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiences'))
    )
    op.create_index(op.f('ix_experiences_company_name'), 'experiences', ['company_name'], unique=False)
    op.create_index(op.f('ix_experiences_worker_id'), 'experiences', ['worker_id'], unique=False)
    op.create_table('facility_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state_province', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('is_headquarters', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_facility_addresses_facility_id_facilities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility_addresses'))
    )
    op.create_index('ix_facaddr_city_state', 'facility_addresses', ['city', 'state_province'], unique=False)
    op.create_index(op.f('ix_facility_addresses_city'), 'facility_addresses', ['city'], unique=False)
    op.create_index(op.f('ix_facility_addresses_country'), 'facility_addresses', ['country'], unique=False)
    op.create_index(op.f('ix_facility_addresses_facility_id'), 'facility_addresses', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facility_addresses_postal_code'), 'facility_addresses', ['postal_code'], unique=False)
    op.create_index(op.f('ix_facility_addresses_state_province'), 'facility_addresses', ['state_province'], unique=False)
    op.create_table('facility_certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Enum('VERIFIED_BUSINESS', 'VERIFIED_HEALTHCARE_PROVIDER', name='facilitycertificationcode'), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'PENDING', 'COMPLETED', 'FAILED', name='verificationstatus'), nullable=False),
    sa.Column('evidence_url', sa.String(length=512), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_facility_certifications_facility_id_facilities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility_certifications')),
    sa.UniqueConstraint('facility_id', 'code', name='uq_facility_certification_once')
    )
    op.create_index(op.f('ix_facility_certifications_code'), 'facility_certifications', ['code'], unique=False)
    op.create_index(op.f('ix_facility_certifications_facility_id'), 'facility_certifications', ['facility_id'], unique=False)
    op.create_table('facility_specialties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('specialty_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_facility_specialties_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_type_id'], ['specialty_types.id'], name=op.f('fk_facility_specialties_specialty_type_id_specialty_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility_specialties')),
    sa.UniqueConstraint('facility_id', 'specialty_type_id', name='uq_facility_specialty_once')
    )
    op.create_index(op.f('ix_facility_specialties_facility_id'), 'facility_specialties', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facility_specialties_specialty_type_id'), 'facility_specialties', ['specialty_type_id'], unique=False)
    op.create_table('job_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('facility_legal_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state_province', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('position_title', sa.String(length=200), nullable=False),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', name='employmenttype'), nullable=False),
    sa.Column('compensation_type', sa.Enum('HOURLY', 'MONTHLY', 'YEARLY', name='compensationtype'), nullable=False),
    sa.Column('hourly_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hourly_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('yearly_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('yearly_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(hourly_min IS NULL OR hourly_max IS NULL) OR (hourly_min <= hourly_max)', name=op.f('ck_job_posts_ck_job_hourly_min_le_max')),
    sa.CheckConstraint('(monthly_min IS NULL OR monthly_max IS NULL) OR (monthly_min <= monthly_max)', name=op.f('ck_job_posts_ck_job_monthly_min_le_max')),
    sa.CheckConstraint('(yearly_min IS NULL OR yearly_max IS NULL) OR (yearly_min <= yearly_max)', name=op.f('ck_job_posts_ck_job_yearly_min_le_max')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_job_posts_facility_id_facilities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_posts'))
    )
    op.create_index(op.f('ix_job_posts_city'), 'job_posts', ['city'], unique=False)
    op.create_index('ix_job_posts_city_state', 'job_posts', ['city', 'state_province'], unique=False)
    op.create_index(op.f('ix_job_posts_compensation_type'), 'job_posts', ['compensation_type'], unique=False)
    op.create_index(op.f('ix_job_posts_employment_type'), 'job_posts', ['employment_type'], unique=False)
    op.create_index(op.f('ix_job_posts_facility_id'), 'job_posts', ['facility_id'], unique=False)
    op.create_index(op.f('ix_job_posts_position_title'), 'job_posts', ['position_title'], unique=False)
    op.create_index(op.f('ix_job_posts_postal_code'), 'job_posts', ['postal_code'], unique=False)
    op.create_index(op.f('ix_job_posts_state_province'), 'job_posts', ['state_province'], unique=False)
    op.create_table('safety_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('TIER1', 'TIER2', 'TIER3', name='safetytier'), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'PENDING', 'COMPLETED', 'FAILED', name='verificationstatus'), nullable=False),
    sa.Column('evidence_url', sa.String(length=512), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_safety_checks_worker_id_workers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_safety_checks'))
    )
    op.create_index(op.f('ix_safety_checks_worker_id'), 'safety_checks', ['worker_id'], unique=False)
    op.create_table('worker_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('credential_type_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=120), nullable=True),
    sa.Column('jurisdiction', sa.String(length=120), nullable=True),
    sa.Column('evidence_url', sa.String(length=512), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credential_type_id'], ['credential_types.id'], name=op.f('fk_worker_credentials_credential_type_id_credential_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_worker_credentials_worker_id_workers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_credentials')),
    sa.UniqueConstraint('worker_id', 'credential_type_id', name='uq_worker_credential_unique')
    )
    op.create_index(op.f('ix_worker_credentials_worker_id'), 'worker_credentials', ['worker_id'], unique=False)
    op.create_table('job_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_post_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('contact_phone_e164_snapshot', sa.String(length=32), nullable=True),
    sa.Column('contact_email_snapshot', sa.String(length=254), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], name=op.f('fk_job_applications_job_post_id_job_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_job_applications_worker_id_workers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_applications')),
    sa.UniqueConstraint('job_post_id', 'worker_id', name='uq_one_application_per_worker_job')
    )
    op.create_index(op.f('ix_job_applications_contact_email_snapshot'), 'job_applications', ['contact_email_snapshot'], unique=False)
    op.create_index(op.f('ix_job_applications_contact_phone_e164_snapshot'), 'job_applications', ['contact_phone_e164_snapshot'], unique=False)
    op.create_index(op.f('ix_job_applications_job_post_id'), 'job_applications', ['job_post_id'], unique=False)
    op.create_index(op.f('ix_job_applications_status'), 'job_applications', ['status'], unique=False)
    op.create_index(op.f('ix_job_applications_worker_id'), 'job_applications', ['worker_id'], unique=False)
    op.create_index('ix_job_apps_worker_status', 'job_applications', ['worker_id', 'status'], unique=False)
    op.create_table('job_post_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_post_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('RN', 'LPN', 'CNA', 'CAREGIVER', 'SUPPORT', name='workertitle'), nullable=False),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], name=op.f('fk_job_post_roles_job_post_id_job_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_post_roles')),
    sa.UniqueConstraint('job_post_id', 'role', name='uq_job_post_role_once')
    )
    op.create_index(op.f('ix_job_post_roles_job_post_id'), 'job_post_roles', ['job_post_id'], unique=False)
    op.create_index(op.f('ix_job_post_roles_role'), 'job_post_roles', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_post_roles_role'), table_name='job_post_roles')
    op.drop_index(op.f('ix_job_post_roles_job_post_id'), table_name='job_post_roles')
    op.drop_table('job_post_roles')
    op.drop_index('ix_job_apps_worker_status', table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_worker_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_status'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_job_post_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_contact_phone_e164_snapshot'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_contact_email_snapshot'), table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_worker_credentials_worker_id'), table_name='worker_credentials')
    op.drop_table('worker_credentials')
    op.drop_index(op.f('ix_safety_checks_worker_id'), table_name='safety_checks')
    op.drop_table('safety_checks')
    op.drop_index(op.f('ix_job_posts_state_province'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_postal_code'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_position_title'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_facility_id'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_employment_type'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_compensation_type'), table_name='job_posts')
    op.drop_index('ix_job_posts_city_state', table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_city'), table_name='job_posts')
    op.drop_table('job_posts')
    op.drop_index(op.f('ix_facility_specialties_specialty_type_id'), table_name='facility_specialties')
    op.drop_index(op.f('ix_facility_specialties_facility_id'), table_name='facility_specialties')
    op.drop_table('facility_specialties')
    op.drop_index(op.f('ix_facility_certifications_facility_id'), table_name='facility_certifications')
    op.drop_index(op.f('ix_facility_certifications_code'), table_name='facility_certifications')
    op.drop_table('facility_certifications')
    op.drop_index(op.f('ix_facility_addresses_state_province'), table_name='facility_addresses')
    op.drop_index(op.f('ix_facility_addresses_postal_code'), table_name='facility_addresses')
    op.drop_index(op.f('ix_facility_addresses_facility_id'), table_name='facility_addresses')
    op.drop_index(op.f('ix_facility_addresses_country'), table_name='facility_addresses')
    op.drop_index(op.f('ix_facility_addresses_city'), table_name='facility_addresses')
    op.drop_index('ix_facaddr_city_state', table_name='facility_addresses')
    op.drop_table('facility_addresses')
    op.drop_index(op.f('ix_experiences_worker_id'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_company_name'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_endorsements_worker_id'), table_name='endorsements')
    op.drop_index(op.f('ix_endorsements_facility_id'), table_name='endorsements')
    op.drop_table('endorsements')
    op.drop_index('ix_workers_title_state', table_name='workers')
    op.drop_index('ix_workers_title_city', table_name='workers')
    op.drop_index(op.f('ix_workers_title'), table_name='workers')
    op.drop_index(op.f('ix_workers_state_province'), table_name='workers')
    op.drop_index(op.f('ix_workers_postal_code'), table_name='workers')
    op.drop_index(op.f('ix_workers_full_name'), table_name='workers')
    op.drop_index(op.f('ix_workers_city'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_specialty_types_code'), table_name='specialty_types')
    op.drop_table('specialty_types')
    op.drop_index(op.f('ix_facilities_phone_e164'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_legal_name'), table_name='facilities')
    op.drop_index('ix_facilities_industry_state', table_name='facilities')
    op.drop_index('ix_facilities_industry_city', table_name='facilities')
    op.drop_index(op.f('ix_facilities_industry'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_hq_state_province'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_hq_postal_code'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_hq_country'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_hq_city'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_credential_types_code'), table_name='credential_types')
    op.drop_table('credential_types')
    # ### end Alembic commands ###
